### ISSUE TITLE
CLI parameters not always well parsed with docker

### ISSUE THREAD

**Issue by IMSdevsecu** [bluecmd/fortigate_exporter#126]
Hi,

I have run into a strange situation where CLI parameters are not parsed/processed with docker-compose. In my case `-max-vpn-users`.

When running docker-compose.yml :
```yaml
fortigate-exporter:
  image: quay.io/bluecmd/fortigate_exporter:latest
  container_name: fortigate-exporter
  command:
    - "-auth-file"
    - "/config/fortigate-key.yaml"
    - "-insecure"
    - "true"
    - "-max-vpn-users"
    - "1000"
  volumes:
    - ./fortigate-key.yaml:/config/fortigate-key.yaml
  restart: always
  ports:
    - "127.0.0.1:9710:9710"
```

I see the process command line running on the system:
```
./fortigate-exporter -auth-file /config/fortigate-key.yaml -insecure true -max-vpn-users 1000
```

Nothing is returned for `fortigate_vpn_users` metric. I have less than 1000 VPN SSL users on firewall I am scraping and some users should be returned.

Moving the parameter earlier in the CLI parameters list and this is working fine:
```yaml
fortigate-exporter:
  image: quay.io/bluecmd/fortigate_exporter:latest
  container_name: fortigate-exporter
  command:
    - "-auth-file"
    - "/config/fortigate-key.yaml"
    - "-max-vpn-users"
    - "1000"
    - "-insecure"
    - "true"
  volumes:
    - ./fortigate-key.yaml:/config/fortigate-key.yaml
  restart: always
  ports:
    - "127.0.0.1:9710:9710"
```

No issue while running directly the command line from compiled code (commit a9034 aka v1.10.0):
```
./target/fortigate-exporter -auth-file ../fortigate-key.yaml -insecure true -max-vpn-users 1000
```

When runing directly with docker command:
```
docker run -p 9710:9710 -v /<my_path>/fortigate-key.yaml:/config/fortigate-key.yaml quay.io/bluecmd/fortigate_exporter:latest -auth-file /config/fortigate-key.yaml -max-vpn-users 1000 -insecure true
#OK

docker run -p 9710:9710 -v /<my_path>/fortigate-key.yaml:/config/fortigate-key.yaml quay.io/bluecmd/fortigate_exporter:latest -auth-file /config/fortigate-key.yaml -insecure true -max-vpn-users 1000
#NOT OK

docker run -p 9710:9710 -v /<my_path>/fortigate-key.yaml:/config/fortigate-key.yaml quay.io/bluecmd/fortigate_exporter:latest -auth-file /config/fortigate-key.yaml -insecure true -max-vpn-users 1000 -test
#NOT OK
```

Last docker test makes me think that the problem is more with the exporter than docker of docker-compose.
Issue seems to be with handeling the last parameter, but not when this is `insecure`.

This is working fine with compiled code directly without docker.
Am I missing something about docker/docker-compose ?
I have found no reason why the exporter parameters parsing whould handle last parameters differently.

Running:
Docker version 18.09.1
docker-compose version 1.21.0
