### ISSUE TITLE
dial tcp [::1]:9710: connect: cannot assign requested address

### ISSUE THREAD

**Issue by blanosko** [bluecmd/fortigate_exporter#149]
Hi,

I have some problem with exporter reaching my Fortigate:
![image](https://user-images.githubusercontent.com/26611576/137339690-90f60e6c-0ab3-4795-b9b7-e9fa77a9e760.png)

I cannot establish connection to FortiGate. Tried it with -insecure or -auth-file or without, still showing same error. Can someone have look at this? My config is below:

docker-compose.yml
 
```
fortigate_exporter:
    image: quay.io/bluecmd/fortigate_exporter:master
    container_name: fortigate_exporter
    ports:
      - "9710:9710"
    volumes:
      - /etc/fortigate_exporter/:/config/
    restart: unless-stopped
    command:
      - "-insecure"
      - "-auth-file=/config/fortigate-key.yaml"

```
     
prometheus.yml

```
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'fortigate_exporter'
    metrics_path: /probe
    static_configs:
      - targets:
        - https://<IP OF FORTIGATE>:4433
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
        # Drop the https:// and port (if specified) for the 'instance=' label
        regex: '(?:.+)(?::\/\/)([^:]*).*'
      - target_label: __address__
        replacement: '[::1]:9710'
```

fortigate-key.yml

```
"https://<IP OF FORTIGATE>:4433":
  token: <VALID TOKEN>
```

Thanks for help guys!
