### ISSUE TITLE
how to use -insecure with docker?

### ISSUE THREAD

**Issue by burgerwhore** [bluecmd/fortigate_exporter#151]
New to docker, portioner, and prometheus.  In my logs I see it complaining about the "IP SANs" and from other issues it sounds like I need it use -insecure but I'm not sure how to add/build with that enabled?
I tried something as simple as 
docker run -d -p 9710:9710 -v /srv/prometheus/fortigate-key.yaml:/config/fortigate-key.yaml quay.io/bluecmd/fortigate_exporter:master -insecure
But that didn't work.
Thanks.

**Comment by jbergquist** [comment]
Hey,

If you are using plain ol' docker you need to do:

`$> docker run -d -p 9710:9710 -v /srv/prometheus/fortigate-key.yaml:/config/fortigate-key.yaml quay.io/bluecmd/fortigate_exporter:master -auth-file /config/fortigate-key.yaml -insecure`

and if you use docker-compose:

```
  fortigate-exporter:
    image: quay.io/bluecmd/fortigate_exporter:master
    user: 10001:10001
    hostname: fortigate-exporter
    container_name: fortigate-exporter
    environment:
      - TZ='Europe/London'
    volumes:
      - /srv/prometheus/fortigate-key.yaml:/config/fortigate-key.yaml
    command: ["-auth-file", "/config/fortigate-key.yaml", "-insecure"]
```
