### ISSUE TITLE
Unable to deploy config on Phrometeus

### ISSUE THREAD

**Issue by simposiummm** [bluecmd/fortigate_exporter#172]
Hi

Sorry but i loose more than 3h to understand how is the config in Prometheus file with the example that is on the wiki.
This is my configuration, i just want to connect to a fortigate on the https://192.168.1.121

  - job_name: 'fortigate_exporter'
    metrics_path: /probe
    static_configs:
      - targets:
        - https://192.168.1.121
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
        # Drop the https:// and port (if specified) for the 'instance=' label
        regex: '(?:.+)(?::\/\/)([^:]*).*'
      - target_label: __address__
        replacement: '[::1]:9710'

I can not understand and always i get the same error on the GUI for Prometheus see below

![image](https://user-images.githubusercontent.com/62385029/174133069-635a70c1-5bcd-40f8-8ab1-ee85a8332e98.png)

Please please please could you give me advise and let us know to standard users how to make it works, the information on the wiki is not enough =(

**Comment by bluecmd** [comment]
Is the exporter running in the server as Prometheus? You have told it to reach the exporter on `::1` (IPv6 localhost) on port 9710

**Comment by simposiummm** [comment]
> Is the exporter running in the server as Prometheus? You have told it to reach the exporter on `::1` (IPv6 localhost) on port 9710

Hi

The exporter is running on a docker so this where came the complex, I'm not sure how to make it work, see below the details 

![image](https://user-images.githubusercontent.com/62385029/174258950-b41af548-ad4e-4d39-bc17-38964d86eda5.png)

**Comment by Lunaden** [comment]
If within a stack, you can use the service name of the container
``` yml
# Compose File
   fortigateexporterservicename:
    image: quay.io/bluecmd/fortigate_exporter:latest
    restart: unless-stopped
    volumes:
      - /containers/tig/fortigate-exporter/fortigate-key.yaml:/config/fortigate-key.yaml
    #ports:
      #- 9710:9710
    command: ["-auth-file", "/config/fortigate-key.yaml", "-insecure"]
```
```yml
# Prometheus config file
  - job_name: 'fortigate_exporter'
    metrics_path: /probe
    static_configs:
      - targets:
        - https://192.168.1.121
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
        # Drop the https:// and port (if specified) for the 'instance=' label
        regex: '(?:.+)(?::\/\/)([^:]*).*'
      - target_label: __address__
        replacement: 'fortigateexporterservicename:9710'
```
