### ISSUE TITLE
Probe request rejected: Error is: no API authentication registered for My Fortigate device

### ISSUE THREAD

**Issue by zxrmxn** [bluecmd/fortigate_exporter#232]
I'm kinda new in using Prometheus and Fortigate let alone REST API, but I want to try to use this exporter for some of my workplace projects. Since my workplace using Fortigate, and with some research I found this exporter to scrape Fortigate metrics to be then displayed on Grafana. Long story short I managed installed Prometheus on my sandbox server, until the time I install the exporter and run the exporter, but I always got an error like this:
**Probe request rejected; Error is: no API authentication registered for "https://10.118.10.254"**

I've read some other people that have this kind of issue like #223 and #201 but seems like there's no resolution.

Like #223, if I visit https://10.118.10.254/api/v2/monitor/system/status?access_token=tokenhere I get an API response and it returns the data.

I also tried curl
``curl -vvv -k -H "Authorization: tokenhere " "https://10.118.10.254/api/v2/cmdb/firewall/address/"``
which returns this:

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>401 Unauthorized</title>
</head><body>
<h1>Unauthorized</h1>
<p>This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.</p>
<p>Additionally, a 401 Unauthorized
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>
* Connection #0 to host 10.118.10.254 left intact
```

I don't know if I'm doing something wrong on fortigate-key.yaml or my Fortigate REST API setup since it's my first time handle both Fortigate and Prometheus.

FYI this is some of the information about my systems and configurations
- Fortigate: 100F with 6.2.12 FortiOS
- Server: Ubuntu Server that host both Prometheus and the exporter

**Prometheus Configuration**
```
# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'fortigate_exporter'
    metrics_path: /probe
    static_configs:
      - targets:
        - https://10.118.10.254
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
        # Drop the https:// and port (if specified) for the 'instance=' label
        regex: '(?:.+)(?::\/\/)([^:]*).*'
      - target_label: __address__
        replacement: '[::1]:9710'
```
**Fortigate Configuration**
```
config system accprofile
    edit "monitor"
        set authgrp read
        set fwgrp read
        set loggrp read
        set netgrp read
        set sysgrp read
        set vpngrp read
        set wifi read
    next
end
```

**fortigate-key.yaml Configuration**
```
"https://10.118.10.254":
  token: tokenhere
  probes:
    include:
      - System
      - VPN
      - Firewall/Policies
```

Thank You!
