### ISSUE TITLE
Help in mounting/copy fortigate-key.yaml file to image itself

### ISSUE THREAD

**Issue by faizansyed66** [bluecmd/fortigate_exporter#252]
Hi @bluecmd  ,
Can you please help me with your advice on mounting fortigate-key.yaml file directly inside the image. Currently I am planning to run the fortigate exporter on PaaS service (Cloud foundary) which does not support volume mounting these files to the container in run time and there is no storage volume to store fortigate-key.yaml. I am thinking is there any way during the build process of the image in the Dockerfile, can we directly push/mount fortigate-key.yaml and create the image out of it. 
I use below copy command in the dockerfile but its not working. Can you suggest something here?

```
FROM quay.io/bluecmd/fortigate_exporter:master
COPY ./my-local-dir/fortigate-key.yaml /config/fortigate-key.yaml

```

@bluecmd @j-oss2023 @lazyb0nes
Need your advice in here on creating docker file

**Comment by j-oss2023** [comment]
I guess your docker build looks right... 

but how have you setup your docker compose

see below

```yaml
  fortigate_exporter:
    restart: always
    # image: quay.io/bluecmd/fortigate_exporter
    image: fortigate_exporter # your custom image
    command: ["-auth-file", "/config/fortigate-key.yaml", "-insecure"]
```

**Comment by faizansyed66** [comment]
Hi @j-oss2023 ,
Thank you for your reply, After hardening the fortigate-key.yaml file inside the image, I am just running this image in cloud foundary or we can say that I want to use simple docker run command like ``docker run -it fortigate_exporter -p 9710:0710 `` 
Using below manifest in cloud foundry but getting error as : no such file or directory 

```
applications:
- name: fortigate # name of your application
  memory: 1G 
  disk_quota: 1G
  instances: 1
  port: "9710:9710"
  docker:
    image: faizans/test:latest  # my customized image
  command: -auth-file /config/fortigate-key.yaml -insecure

```
