### ISSUE TITLE
Getting response conde 429

### ISSUE THREAD

**Issue by hiepnh610** [bluecmd/fortigate_exporter#256]
Hi,
I am encountering an issue while attempting to export data for monitoring on my 50E. Instead of receiving the expected HTTP status code 200, I am consistently receiving error code 429, indicating too many requests. I suspect there may be an error in the steps I have taken, and I am seeking assistance in identifying and resolving the root cause of this issue. Your guidance in addressing this matter would be greatly appreciated.

```
# Environment

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

Docker version 24.0.7, build afdd53b

Docker Compose version v2.21.0
```

```
# I access to http://10.0.10.209:9710/probe?target=https%3A%2F%2F10.0.0.1 and get those messages.

# HELP probe_duration_seconds How many seconds the probe took to complete
# TYPE probe_duration_seconds gauge
probe_duration_seconds 0.026154833
# HELP probe_success Whether or not the probe succeeded
# TYPE probe_success gauge
probe_success 0
```

```
# These logs originate from within a Docker container.

➜ prometheus docker logs fortigate_exporter
2023/11/30 02:18:26 FortigateExporter 1.23.0-2-g9d74331 ( 9d74331 )
2023/11/30 02:18:26 Loaded 1 API keys
2023/11/30 02:18:26 Fortigate exporter running, listening on ":9710"
2023/11/30 02:19:14 Error: API connectivity test failed, Response code was 429, expected 200 (path: "api/v2/monitor/system/status")
2023/11/30 02:19:14 Probe of "https://10.0.0.1" failed, took 0.027 seconds
2023/11/30 02:19:45 Error: API connectivity test failed, Response code was 429, expected 200 (path: "api/v2/monitor/system/status")
2023/11/30 02:19:45 Probe of "https://10.0.0.1" failed, took 0.027 seconds
2023/11/30 02:20:14 Error: API connectivity test failed, Response code was 429, expected 200 (path: "api/v2/monitor/system/status")
2023/11/30 02:20:14 Probe of "https://10.0.0.1" failed, took 0.026 seconds
2023/11/30 02:21:14 Error: API connectivity test failed, Response code was 429, expected 200 (path: "api/v2/monitor/system/status")
2023/11/30 02:21:14 Probe of "https://10.0.0.1" failed, took 0.027 seconds
2023/11/30 02:22:14 Error: API connectivity test failed, Response code was 429, expected 200 (path: "api/v2/monitor/system/status")
2023/11/30 02:22:14 Probe of "https://10.0.0.1" failed, took 0.026 seconds
```

```yaml
# My docker compose
---
version: "3.8"

services:
  prometheus:
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    container_name: prometheus
    image: prom/prometheus:latest
    restart: unless-stopped
    user: root
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - ./data:/prometheus
    depends_on:
      - cadvisor
      - node_exporter
      - adguard_exporter
      - fortigate_exporter
    networks:
      - prometheus

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    privileged: true
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    networks:
      - prometheus

  fortigate_exporter:
    container_name: fortigate_exporter
    image: quay.io/bluecmd/fortigate_exporter:master
    restart: unless-stopped
    command: ["-auth-file", "/config/fortigate-key.yaml", "-insecure"]
    volumes:
      - ./fortigate-key.yaml:/config/fortigate-key.yaml
    ports:
      - 9710:9710
    networks:
      - prometheus

  node_exporter:
    command: "--path.rootfs=/host"
    container_name: node_exporter
    image: quay.io/prometheus/node-exporter:latest
    pid: host
    restart: unless-stopped
    ports:
      - 9100:9100
    volumes:
      - /:/host:ro,rslave
    networks:
      - prometheus

  adguard_exporter:
    container_name: adguard_exporter
    image: ebrianne/adguard-exporter:latest
    restart: unless-stopped
    ports:
      - "9617:9617"
    environment:
      - adguard_protocol=http
      - adguard_hostname=${ADGUARD_HOST}
      - adguard_username=${ADGUARD_USERNAME}
      - adguard_password=${ADGUARD_PASSWORD}
      - interval=10s
      - log_limit=10000
      - server_port=9617
    networks:
      - prometheus

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - prometheus


volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

networks:
  prometheus:
    driver: bridge
```

```yaml
# fortigate-key.yaml

"https://10.0.0.1":
  token: my-token-generate-from-my-fortigate-device
  probes:
    include:
      - System
      - Firewall
```

```yaml
# Prometheus configuration
global:
  scrape_interval: 1m

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #  monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100', '10.0.10.210:9100']

  - job_name: 'adguard_exporter'
    static_configs:
      - targets: ['adguard_exporter:9617']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'Mikrotik'
    static_configs:
      - targets:
        - 10.0.10.1
    metrics_path: /snmp
    params:
      module: [mikrotik]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.0.10.209:9116

  - job_name: 'fortigate_exporter'
    metrics_path: /probe
    static_configs:
      - targets:
        - https://10.0.0.1
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
        # Drop the https:// and port (if specified) for the 'instance=' label
        regex: '(?:.+)(?::\/\/)([^:]*).*'
      - target_label: __address__
        replacement: '10.0.10.209:9710'
```
