### ISSUE TITLE
[Help - Container] Connection refuse from Prometheus target status

### ISSUE THREAD

**Issue by DevDorrejo** [bluecmd/fortigate_exporter#276]
Hello, i have setup a rootless environment with podman (Share the code if someone need it):

```
#!/usr/bin/env bash
# -*- coding: utf-8 -*-

# Network container creation
if ! podman network ls | grep -q monitor; then
  podman network create monitor
fi

# Volume Management
## This will point the mount to the folder and store the info there
folders=(
  "grafana/data"
  "prometheus/data"
  "prometheus/config"
  "prometheus/fortigate"
)
paths="${PWD}/volume"
for d in "${folders[@]}"; do
  if [ ! -d "${paths}/${d}" ]; then
    mkdir -p "${paths}/${d}"
  fi
  podman volume create \
    -o type=none \
    -o device="${paths}/${d}" \
    -o=o=bind \
    "${d%%/*}-${d#*/}"
done

# Credentials
PASS=$(openssl rand -base64 12) && echo "$PASS"
# mkdir -p "${PWD}"/.enc && echo "${PASS}" >.enc/pass && podman secret create "$(echo "${PASS}" | openssl enc -e -a -base64 | sed 's/[^a-zA-Z0-9]*$//')" .enc/pass
mkdir -p "${PWD}"/.enc && echo "${PASS}" >.enc/pass && podman secret create pass-secret .enc/pass

# Pod Creation
podman pod create \
  --replace \
  --restart unless-stopped \
  -h "Hostname" \
  -n "podName" \
  --network "monitor" \
  --infra-name "InfraName (Optional)" \
  -p 127.0.0.1:3000:3000 \
  -p 127.0.0.1:9090:9090

# Grafana
podman run -d \
  --replace \
  --pull=always \
  --label "io.containers.autoupdate=registry" \
  --user "$(id -u)" \
  --name grafana \
  --pod "PodName" \
  --secret pass-secret \
  -v grafana-data:/var/lib/grafana:U \
  -e "GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/pass-secret" \
  -e "GF_DEFAULT_INSTANCE_NAME=EYES" \
  -e "GF_SERVER_ENABLE_GZIP=true" \
  -e "GF_FEATURE_TOGGLES_ENABLE=publicDashboards" \
  -e "GF_INSTALL_PLUGINS=grafana-clock-panel, citilogics-geoloop-panel, gowee-traceroutemap-panel, alexanderzobnin-zabbix-app" \
  -e "GF_LOG_MODE=console file" \
  docker.io/grafana/grafana-enterprise

# Prometheus setup

## Prometheus
podman run -d \
  --replace \
  --pull=always \
  --label "io.containers.autoupdate=image" \
  --name prometheus \
  --pod "PodName" \
  -v prometheus-data:/prometheus:U \
  -v prometheus-config:/etc/prometheus:U \
  docker.io/prom/prometheus \
  --config.file=/etc/prometheus/prometheus.yml \
  --storage.tsdb.path=/prometheus \
  --web.console.libraries=/etc/prometheus/console_libraries \
  --web.console.templates=/etc/prometheus/consoles \
  --web.enable-lifecycle

## prometheus.yml
# Prometheus file configuration

cat >>"${paths}"/"${folders[2]}"/prometheus.yml <<EOF
# Prometheus.YML version 1
global:
  scrape_interval: 15s
  evaluation_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  # The job name is added as a label \`job=<job_name>\` to any timeseries scraped from this config.
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  # Example
  - job_name: "Example"
    scrape_interval: 5s
    static_configs:
      - targets: ["node_exporter:9100"]
        labels:
          group: "Example"
  
# Alertmanager configuration
#alerting:
#  alertmanagers:
#    - static_configs:
#    - targets:
  # - alertmanager:9093

EOF

## Node_export (For openSUSE host)
zypper in -y podman systemd-container
firewall-cmd --permanent --add-port=9100/tcp && firewall-cmd --reload

set -- nodeProm
useradd -c "$1 Manager User" -md /opt/"$1" -U "$1"
loginctl enable-linger "$1"
machinectl shell "$1"@

cp -R /usr/share/containers .config/
sed -i '0,/"journald"/s,,"k8s-file",' "${HOME}"/.config/containers/containers.conf

podman run -d \
  --replace \
  --pull=newer \
  --label "io.containers.autoupdate=registry" \
  --name node_exporter \
  --cap-add=SYS_TIME \
  --pid="host" \
  --net="host" \
  -v "/:/rootfs:ro,rslave" \
  -v "/proc:/host/proc:ro,rslave" \
  -v "/sys:/host/sys:ro,rslave" \
  docker.io/prom/node-exporter \
  --path.procfs=/host/proc \
  --path.rootfs=/rootfs \
  --path.sysfs=/host/sys \
  '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

# Fortigate Exporter
podman run -d \
  --replace \
  --pull=newer \
  --label "io.containers.autoupdate=registry" \
  --name foti_exporter \
  --pid="host" \
  --net="monitor" \
  -v prometheus-fortigate:/config \
  -p 9710:9710 \
  quay.io/bluecmd/fortigate_exporter -insecure -auth-file="/config/fortigate-key.yaml"

```

Here is the Fortigate Exporter:
```
podman run -d \
  --replace \
  --pull=newer \
  --label "io.containers.autoupdate=registry" \
  --name foti_exporter \
  --pid="host" \
  --net="monitor" \
  -v prometheus-fortigate:/config \
  -p 9710:9710 \
  quay.io/bluecmd/fortigate_exporter -insecure -auth-file="/config/fortigate-key.yaml"
```

fortigate-key.yaml:
```
 "https://10.0.0.2":
     token: TokenAPI
     probes:
         exclude:
             - Wifi                                                                                                                                                                                                                               
             - Firewall/LoadBalance

```

Prometheus:
```
# Prometheus.YML version 1
 global:
   scrape_interval: 15s
   evaluation_interval: 30s
   scrape_timeout: 10s
 
 scrape_configs:
   - job_name: "FortigateExporter"
     metrics_path: /probe
     scrape_interval: 5s
     static_configs:
         - targets:
             - "https://10.0.0.2"
     relabel_configs:
         - source_labels: [__address__]
           target_label: __param_target
         - source_labels: [__param_target]
           target_label: instance
           regex: '(?:.+)(?::\/\/)([^:]*).*'
         - target_label: __address__
           replacement: '127.0.0.1:9710'

```

but when i go to "prometheus:9090/targets?search=FortigateExporter, it said connection refuse to the fortigate:
![image](https://github.com/bluecmd/fortigate_exporter/assets/7697566/5ab076b4-1e40-478e-b200-bb3a399c6cc9)

But in the grafana server, where fortigate_exporter container is, I can connect:

`curl -I -X GET http://127.0.0.1:9710/probe?target=https://10.0.0.24`

return:
`HTTP1.1 200 OK`

So, what can I miss to cause connection refuse?
