### ISSUE TITLE
Probe request rejected; error is: Unsupported scheme ""

### ISSUE THREAD

**Issue by raj16120912** [bluecmd/fortigate_exporter#286]
Hi All, I am facing an error `Probe request rejected; error is: Unsupported scheme ""` while probing, debug log shows following error:
```
Apr  8 02:52:38 Prometheus-Server prometheus[222324]: ts=2024-04-08T06:52:38.122Z caller=scrape.go:1274 level=debug component="scrape manager" scrape_pool=fortigate_exporter target="http://prometheus.example.net:9710/probe?target=192.168.0.10" msg="Scrape failed" err="server returned HTTP status 400 Bad Request"
```
Here's my prometheus config
```
## Firewall section
  - job_name: 'fortigate_exporter'
    metrics_path: /probe
    static_configs:
               - targets: ['192.168.0.10']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
        # Drop the https:// and port (if specified) for the 'instance=' label
        regex: '(?:.+)(?::\/\/)([^:]*).*'
      - target_label: __address__
        replacement: prometheus.example.net:9710
```
And, here's my fortigate-key.yml
```
[root@Den-Promth-Server rpatil]# cat /etc/fortigate-key.yaml
"https://192.168.0.10":
  token: xxxxxxxxxxxxxxxxx
  # If you have a smaller fortigate unit you might want
  # to exclude sensors as they do not have any
  probes:
    include:
      - System
      - Firewall
```
Here is the curl command output
```
[root@Prometheus-Server]# curl 'localhost:9710/probe?target=https://192.168.0.10&token=xxxxxxxxxxxxxxxxxxxx'
# HELP probe_duration_seconds How many seconds the probe took to complete
# TYPE probe_duration_seconds gauge
probe_duration_seconds 0.101268513
# HELP probe_success Whether or not the probe succeeded
# TYPE probe_success gauge
probe_success 0
```
fortigate exporter is running on prometheus server itself and network connectivity between prometheus and firewall is fine. 
Can anyone help me out to fix this issue?

Thanks and Regards,
RajP
