### ISSUE TITLE
Unable to probe a device

### ISSUE THREAD

**Issue by UAnton** [bluecmd/fortigate_exporter#31]
How can I build fortigate_exporter without Docker?
Can't get a working exporter :(

```
root@b-prometheus:/etc/prometheus# curl 'localhost:9710/probe?target=https://10.108.48.1'
# HELP probe_duration_seconds How many seconds the probe took to complete
# TYPE probe_duration_seconds gauge
probe_duration_seconds 30.000540573
# HELP probe_success Whether or not the probe succeeded
# TYPE probe_success gauge
probe_success 0
```

**Comment by bluecmd** [comment]
Sure, building without docker is just `go build` as usual.

How does you configuration file look like? How do you start the exporter?

**Comment by agesta23** [comment]
I have same issue : 
curl 'localhost:9710/probe?target=https://10.128.231.1:4434'
# HELP probe_duration_seconds How many seconds the probe took to complete
# TYPE probe_duration_seconds gauge
probe_duration_seconds 0.921026424
# HELP probe_success Whether or not the probe succeeded
# TYPE probe_success gauge
probe_success 0

Prometheus returns : server returned HTTP status 401 Unauthorized , but I do have configured fortigate-key.yaml.
Here is prometheus config snippet : 
 - job_name: 'fortigate_exporter'
    metrics_path: /probe
    static_configs:
    - targets: ['10.128.231.1:4434']
    scheme: https
    tls_config:
      insecure_skip_verify: true

**Comment by bluecmd** [comment]
Hi @agesta23 - could you include the logs from the exporter?

Your curl seems fine and should work, but your Prometheus static_configs section is missing the https:// part of the target.

**Comment by agesta23** [comment]
Hi @bluecmd 
Here is logs from exporter : 
```
2021/02/02 14:29:31 Loaded 1 API keys
2021/02/02 14:29:31 Fortigate exporter running, listening on ":9710"
2021/02/02 14:29:42 Probe request rejected; error is: url.Parse failed: parse "https://'10.128.231.1:4434'": invalid port ":4434'" after host
```

..and changed prometheus config : 
```
- job_name: 'fortigate_exporter'
    static_configs:
    - targets:
        - https://'10.128.231.1:4434'
    metrics_path: /probe
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
        regex: '(?:.+)(?::\/\/)([^:]*).*'
      - target_label: __address__
        replacement: '127.0.0.1:9710'
```
