### ISSUE TITLE
prometheus job target use only ip address @support

### ISSUE THREAD

**Issue by toggit** [bluecmd/fortigate_exporter#84]
do i must supply https in the targets name like target = ['http:\\192.168.100.254']?
what if i already have firewall targets list with the ip only target = ['192.168.100.254']?
i want to be able to reuse this firewall_devices.yml with targets list for diffrent exporters
so if i hard coded https its will not be useable in blackbox_exporter for example.

how can manipulate this config to add https on the fly. and let the targets labels to hold the ip 

i am using file_sd_configs in config file - prometheus.yml :
```
  - job_name: 'fortigate-from-vlan100'
    metrics_path: /probe
    file_sd_configs:
      - files: ['targets/firewall_devices.yml']
    relabel_configs:
      - source_labels: [vlan]
        regex: '100'
        action: keep
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.100.15:9710 #  fortigate exporter ip address to scrap from - vlan 100 only
```

and the targets file look like that - firewall_devices.yml
```
- targets: ["192.168.100.254"]	
  labels: 
    name: NY-FortiGate01
    group: firewall
    location: NY
    vlan: 100

- targets: ["192.168.200.254"]	
  labels: 
    name: NY-Fortigate02
    group: firewall
    location: NY
    vlan: 200
```

maybe its can be resolve on the promethus relab_configs idk... #

**Comment by bluecmd** [comment]
Hello.

Indeed, you can probably change your relabel_config to be something like:
```
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
        replacement: 'https://$1'
```

Untested, but something like that should work.
